uint8_t iADC(uint8_t instr, uint8_t*, uint16_t);
uint8_t iADC(uint8_t instr, uint8_t*, uint8_t);
uint8_t iADC(uint8_t instr, uint8_t*, uint8_t*);
uint8_t iADD(uint8_t instr, uint16_t*, int8_t);
uint8_t iADD(uint8_t instr, uint16_t*, uint16_t*);
uint8_t iADD(uint8_t instr, uint8_t*, uint16_t);
uint8_t iADD(uint8_t instr, uint8_t*, uint8_t);
uint8_t iADD(uint8_t instr, uint8_t*, uint8_t*);
uint8_t iAND(uint8_t instr, uint16_t);
uint8_t iAND(uint8_t instr, uint8_t);
uint8_t iAND(uint8_t instr, uint8_t*);
uint8_t iBIT(uint8_t instr, uint8_t, uint16_t);
uint8_t iBIT(uint8_t instr, uint8_t, uint8_t*);
uint8_t iCALL(uint8_t instr, bool, uint16_t);
uint8_t iCALL(uint8_t instr, uint16_t);
uint8_t iCALL(uint8_t instr, uint16_t*, uint16_t);
uint8_t iCCF(uint8_t instr);
uint8_t iCP(uint8_t instr, uint16_t);
uint8_t iCP(uint8_t instr, uint8_t);
uint8_t iCP(uint8_t instr, uint8_t*);
uint8_t iCPL(uint8_t instr);
uint8_t iDAA(uint8_t instr);
uint8_t iDEC(uint8_t instr, uint16_t);
uint8_t iDEC(uint8_t instr, uint16_t*);
uint8_t iDEC(uint8_t instr, uint8_t*);
uint8_t iDI(uint8_t instr);
uint8_t iEI(uint8_t instr);
uint8_t iHALT(uint8_t instr);
uint8_t iINC(uint8_t instr, uint16_t);
uint8_t iINC(uint8_t instr, uint16_t*);
uint8_t iINC(uint8_t instr, uint8_t*);
uint8_t iJP(uint8_t instr, bool, uint16_t);
uint8_t iJP(uint8_t instr, uint16_t);
uint8_t iJP(uint8_t instr, uint16_t*, uint16_t);
uint8_t iJR(uint8_t instr, bool, uint8_t);
uint8_t iJR(uint8_t instr, uint16_t*, uint8_t);
uint8_t iJR(uint8_t instr, uint8_t);
uint8_t iLD(uint8_t instr, uint16_t*, uint16_t);
uint8_t iLD(uint8_t instr, uint16_t*, uint16_t*);
uint8_t iLD(uint8_t instr, uint16_t, uint16_t*);
uint8_t iLD(uint8_t instr, uint16_t, uint8_t);
uint8_t iLD(uint8_t instr, uint16_t, uint8_t*);
uint8_t iLD(uint8_t instr, uint8_t*, uint16_t);
uint8_t iLD(uint8_t instr, uint8_t*, uint8_t);
uint8_t iLD(uint8_t instr, uint8_t*, uint8_t*);
uint8_t iLDD(uint8_t instr, uint16_t, uint8_t*);
uint8_t iLDD(uint8_t instr, uint8_t*, uint16_t);
uint8_t iLDH(uint8_t instr, uint16_t, uint8_t*);
uint8_t iLDH(uint8_t instr, uint8_t*, uint16_t);
uint8_t iLDH(uint8_t instr, uint8_t, uint8_t*);
uint8_t iLDHL(uint8_t instr, uint16_t*, int8_t);
uint8_t iLDI(uint8_t instr, uint16_t, uint8_t*);
uint8_t iLDI(uint8_t instr, uint8_t*, uint16_t);
uint8_t iMAP(uint8_t instr, uint8_t);
uint8_t iNOP(uint8_t instr);
uint8_t iOR(uint8_t instr, uint16_t);
uint8_t iOR(uint8_t instr, uint8_t);
uint8_t iOR(uint8_t instr, uint8_t*);
uint8_t iPOP(uint8_t instr, uint16_t*);
uint8_t iPUSH(uint8_t instr, uint16_t*);
uint8_t iRES(uint8_t instr, uint8_t, uint16_t);
uint8_t iRES(uint8_t instr, uint8_t, uint8_t*);
uint8_t iRET(uint8_t instr);
uint8_t iRET(uint8_t instr, bool);
uint8_t iRET(uint8_t instr, uint16_t*);
uint8_t iRETI(uint8_t instr);
uint8_t iRLC(uint8_t instr, uint16_t);
uint8_t iRLC(uint8_t instr, uint8_t*);
uint8_t iRLE(uint8_t instr, uint16_t);
uint8_t iRLE(uint8_t instr, uint8_t*);
uint8_t iRR(uint8_t instr, uint16_t);
uint8_t iRR(uint8_t instr, uint8_t*);
uint8_t iRRC(uint8_t instr, uint16_t);
uint8_t iRRC(uint8_t instr, uint8_t*);
uint8_t iRST(uint8_t instr, uint8_t);
uint8_t iSBC(uint8_t instr, uint8_t*, uint16_t);
uint8_t iSBC(uint8_t instr, uint8_t*, uint8_t);
uint8_t iSBC(uint8_t instr, uint8_t*, uint8_t*);
uint8_t iSCF(uint8_t instr);
uint8_t iSET(uint8_t instr, uint8_t, uint16_t);
uint8_t iSET(uint8_t instr, uint8_t, uint8_t*);
uint8_t iSLA(uint8_t instr, uint16_t);
uint8_t iSLA(uint8_t instr, uint8_t*);
uint8_t iSRA(uint8_t instr, uint16_t);
uint8_t iSRA(uint8_t instr, uint8_t*);
uint8_t iSRL(uint8_t instr, uint16_t);
uint8_t iSRL(uint8_t instr, uint8_t*);
uint8_t iSTOP(uint8_t instr);
uint8_t iSUB(uint8_t instr, uint8_t*, uint16_t);
uint8_t iSUB(uint8_t instr, uint8_t*, uint8_t);
uint8_t iSUB(uint8_t instr, uint8_t*, uint8_t*);
uint8_t iSWAP(uint8_t instr, uint16_t);
uint8_t iSWAP(uint8_t instr, uint8_t*);
uint8_t iUNDEF(uint8_t instr);
uint8_t iXOR(uint8_t instr, uint16_t);
uint8_t iXOR(uint8_t instr, uint8_t);
uint8_t iXOR(uint8_t instr, uint8_t*);
